language: node_js
node_js: '9'
cache:
    directories:
     - node_modules
     - electron/downloads
addons:
    artifacts:
        s3_region: "us-west-2"
        debug: true
        paths: $(ls builds/*.zip | tr "\n" ":")
before_install: gem install sass
script: make && make electron-linux
