os:
- osx
- linux
env:
  global:
  - ELECTRON_CACHE=$HOME/.cache/electron
  - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
language: node_js
node_js: '9'
before_cache:
- rm -rf $HOME/.cache/electron-builder/wine
cache:
  directories:
  - node_modules
  - semantic
  - electron/downloads
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
  - $HOME/.npm/_prebuilds
addons:
  artifacts:
    s3_region: us-west-2
    working_dir: builds
    paths: $(ls builds/*-mac.zip builds/*-linux.AppImage builds/*-win.exe | tr "\n" ":")
    target_paths:
    - "/"
before_install:
- gem install sass -v 3.4.23
script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make electron-linux; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make -j electron-mac electron-win; fi
notifications:
  webhooks: https://integration-bot.forsta.io/travisci
