language: node_js
sudo: true
node_js: '9'
cache:
  directories:
  - node_modules
  - electron/downloads
  - semantic
addons:
  artifacts:
    s3_region: us-west-2
    debug: true
    working_dir: builds
    paths: $(ls builds/*.zip builds/*.tar.gz | tr "\n" ":")
    target_paths:
    - "/"
  apt:
    packages:
    - wine
before_install:
- gem install sass
script: make && make electron-linux electron-darwin electron-windows
notifications:
  webhooks: https://integration-bot.forsta.io/travisci
