language: node_js
node_js: '9'
cache:
  directories:
  - node_modules
  - electron/downloads
  - semantic
  - "$HOME/.electron"
addons:
  artifacts:
    s3_region: us-west-2
    debug: true
    working_dir: builds
    paths: $(ls builds/*.zip builds/*.tar.gz | tr "\n" ":")
    target_paths:
    - "/"
before_install: gem install sass
script: make && make electron-linux electron-darwin
notifications:
  webhooks:
    secure: VSJ3E11cqLrskZA1/OhJdeyabc301b47QbULYeRXTwPAuJrl0ouy6jImJkVmRoZN81eiBMnvDyTLf0r4yccJ6X8S2z8m6SYhZybMnWkcvIDDEKrwvQfrdT+I7V3hZi1DHielC1IjVMvfxQHHf/GqPWCvY95eapQGb5SGsQMCaZnl1kMZhqwbExzVei/sS5U/EsY8OLgAM8IwbkeS4cOxBz5+lXshKKGjT0DpX2vVmA0o88tBtH4KIrpLWp7cWSkdeY8DxT3IqmN6kQgJGqZSc/9wPkuEYhTDRVDwPQB9/ASq+E7m+6WgWWJbxyZA9yqcqypRuJWcu+IAIZ9jKLx2VTX40bH655z24NTijhaBbA+pxs4D5XEiuZH6k9/DDYj4WHzeF1ZdRsMPYF5ghoO2mIVSjhRfn+ZnKP4NM91jL7/0HrcBLoN+HWU7LR3ijvMQeXKC8nC/t68mV5L7fMuDFsh86LOX3LHuqc7u/R9sWQKujoof7VV5w3rptymUJxOOkswDPjB6AROHeBkt4/AewA9awlD2N68gFsunZ/mn4bFsUmi1UZ6ejA/MVhcyomnHMk+8elOrKMOIcXTdBI0IfCQaDKIJtLwuKTOrHjLtaMFdXBsRJhzHs+uw7v4KaPvrFkzl/8GYDvA/Ec/HkYIvzpMi2568mMct5QXFOgDbAio=
