language: node_js
node_js: '9'
cache:
    directories:
     - node_modules
     - electron/downloads
     - semantic
     - "$HOME/.electron"
addons:
    artifacts:
        s3_region: "us-west-2"
        debug: true
        working_dir: builds
        paths: $(ls *.zip *.tar.gz | tr "\n" ":")
        target_paths:
         - /ForstaMessageVault-$(npm view . version)
before_install: gem install sass
script: make && make electron-linux electron-darwin
