language: node_js
node_js: '9'
cache:
    directories:
     - node_modules
     - electron/downloads
     - semantic
     - "$HOME/.electron"
addons:
    artifacts:
        s3_region: "us-west-2"
        debug: true
        paths: $(ls builds/*.zip builds/*.tar.gz | tr "\n" ":")
        target_paths:
         - /ForstaMessageVault-$(sw_vers -productVersion | grep --only -E '^[0-9]+\.[0-9]+')
before_install: gem install sass
script: make && make electron-linux electron-darwin
